resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/4.yaml
packages: 
- .
extra-deps:
  - HDBC-sqlite3-2.3.3.1
  - relational-query-0.8.4.0
  - relational-query-HDBC-0.6.0.3
  - persistable-record-0.4.2.0
  - names-th-0.2.0.3
  - relational-schemas-0.1.3.1
  - Spock-0.14.0.0
  - Spock-core-0.14.0.0
  - reroute-0.6.0.0
  - stm-containers-1.2
  - focus-1.0.1.4
  - stm-hamt-1.2.0.4
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0
